spring.application.name=testTruper

spring.datasource.url=jdbc:mariadb://localhost:3307/testTruper
spring.datasource.username=user_sys
spring.datasource.password=12345
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop


# PUERTO MARIA DB 3307